### ISSUE TITLE
Adding SRF

### ISSUE THREAD

**Issue by MTHCH** [Seji64/SniDust#1]
HI there

I love the project. 
Is there any chance to add srf.ch to the domain list? 
Unfortunately,y they have implemented geo-blocking on their lifestream and it would be great when it could be unblocked. 

Thank you for your help!

MTH

**Comment by Seji64** [comment]
Hi,
thanks. glad you like the project.

You can easly extend the domain list by yourself. Just mount your domains file into the docker container:
`
docker run -d -e ALLOWED_CLIENTS="127.0.0.1, PUBLIC_ISP_IP" -e EXTERNAL_IP=PUBLIC_VPS_IP -p 443:443 -p 80:80 -p 53:5300/udp -v /tmp/domains.lst:/opt/myCustomDomainList.lst:ro ghcr.io/seji64/snidust:main`

**Comment by MTHCH** [comment]
Thank you - understood!

**Comment by malex2005** [comment]
Hi! First, my Snidust works fine.when I check myip.is I get my vps ip :)! It looks promising! Thank you so much.  However after a lot of tinkering around, I didn’t manage to add extra domains even with the command above . 

In tmp I have a directory called domains.lst is that normal or should it be a file ? I have created the file myCustomDomainList.lst  in opt but doesn’t seem to do much… can you point me to the right direction?

**Comment by Seji64** [comment]
Oh, in the command I wrote the file mapping the wrong way round.

`docker run -d -e ALLOWED_CLIENTS="127.0.0.1, PUBLIC_ISP_IP" -e EXTERNAL_IP=PUBLIC_VPS_IP -p 443:443 -p 80:80 -p 53:5300/udp -v /opt/myCustomDomainList.lst: /tmp/domains.lst :ro ghcr.io/seji64/snidust:main`

would be correct.
