### ISSUE TITLE
ALLOWED_CLIENTS suggestion/request/recommendation

### ISSUE THREAD

**Issue by EZarnosky** [Seji64/SniDust#10]
The ALLOWED_CLIENTS in the docker run and compose file that you have specified. Would it make more sense to have a AllowedClients.txt file that you can add/remove entries from and SniDust monitors for changes. This would reduce reloads on the container and allow for scripts to update the file should the ISP change the client address. Also I have not tried it yet, but does the ALLOWED_CLIENTS allow for domain names (ex. sub.domain.com) or domain wildcards (e.x *.domain.com)?

**Comment by Seji64** [comment]
I have added this feature to the dev branch. Could test it pls?

PS:
Domain Names are not possible (yet) - must be an ip address or subnet
