### ISSUE TITLE
Downstream marked as down

### ISSUE THREAD

**Issue by ruizabenza** [Seji64/SniDust#17]
Hi!

First of all, thank you for your work! I think it's a very smart solution.

I'm having a problem. I'm running SniDust in my Raspberry Pi and I start it with this command:

`docker run -d --name snidust -e ALLOWED_CLIENTS="127.0.0.1, 192.168.0.0/16" -e EXTERNAL_IP=79.109.127.99 -p 443:443 -p 80:80 -p 53:5300/udp ghcr.io/seji64/snidust:main`

But I have these messages in logs:

> Added downstream server 8.8.8.8:853
> Added downstream server 8.8.4.4:853
> Added downstream server 1.1.1.1:443
> Added downstream server 1.0.0.1:443
> Listening on 0.0.0.0:5300
> dnsdist 1.7.1 comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2
> ACL allowing queries from: 127.0.0.1/32, 192.168.0.0/16
> Console ACL allowing connections from: 127.0.0.0/8, ::1/128
> Webserver launched on 127.0.0.1:8083
> Marking downstream dns.google (8.8.8.8:853) as 'down'
> Marking downstream dns.google (8.8.4.4:853) as 'down'
> Marking downstream 1.1.1.1:443 as 'down'
> Marking downstream 1.0.0.1:443 as 'down'
> Error while retrieving the security update for version dnsdist-1.7.1: Unable to get a valid Security Status update
> Failed to retrieve security status update for '1.7.1' on dnsdist-1.7.1.security-status.secpoll.powerdns.com.
> time=2023-03-06T12:07:10.103Z level=WARN msg="Domain list (--domainListPath) is not specified, routing ALL domains through the SNI proxy"
> time=2023-03-06T12:07:10.104Z level=INFO msg="server info" public_ip=79.109.127.99
> time=2023-03-06T12:07:17.665Z level=INFO msg="Certificate was not provided, using a self signed cert"
> time=2023-03-06T12:07:17.666Z level=INFO msg="Started UDP DNS" service=dns host=0.0.0.0 port=5353

My Raspberry Pi is running behind a router with the ports 443, 80 and 53 opened (Internet <--> Router <--> Raspberry Pi)

I don't know what to check. Could you help me?

Thank you in advance.

**Comment by Seji64** [comment]
Hm looks like your Container does not have Internet access.

Get a shell of your Container with 
`docker exec -it sniDust ash`

and try if you can reach the internet: `ping 8.8.8.8`

If that works test if DNS is working eg.: `curl ifconfig.me`
