### ISSUE TITLE
Could not automatically determine public IPv4

### ISSUE THREAD

**Issue by JiroMusik** [Seji64/SniDust#27]
Hi there, I try to install the SniDust on an arm64 Ubuntu.

I get following errors when running the container:
Error while retrieving the security update for version dnsdist-1.8.0: Unable to get a valid Security Status update
Failed to retrieve security status update for '1.8.0' on dnsdist-1.8.0.security-status.secpoll.powerdns.com.
2023-06-29T11:07:26Z ERR Could not automatically determine public IPv4. you should provide it manually using --publicIPv4
2023-06-29T11:07:26Z ERR Could not automatically determine public IPv6. you should provide it manually using --publicIPv6

Config:
docker run --name snidust -e ALLOWED_CLIENTS="127.0.0.1, PUBIP" -e EXTERNAL_IP=VPSIP -p 443:443 -p 80:80 -p 53:5300/udp -v ~/99-custom.lst:/etc/snidust/domains.d/99-custom.lst:ro ghcr.io/seji64/snidust:main

The VPSIP is specified but why does it not get passed through?

**Comment by Seji64** [comment]
This does not affect SniDust, it is just a message from sniproxy. But indeed this message is confusing.
