### ISSUE TITLE
bypass Great Firewall

### ISSUE THREAD

**Issue by neocortexplus** [Seji64/SniDust#32]
How can I circumvent the Great Firewall set up by my government to access restricted websites such as YouTube or Netflix? With the current settings, I'm unable to do so. However, I can access sites that are prohibited by entities other than my government. is it the solution dns over tls or something like that? how can i enable this?

**Comment by Seji64** [comment]
Hi, i think SniDust is not the best tool for your propose. You better you use something like ShadowSOCKS.... - however you can set `SPOOF_ALL_DOMAINS` to `true` to reach your goal.
