### ISSUE TITLE
docker becames unresponsive after some time

### ISSUE THREAD

**Issue by hogmac** [Seji64/SniDust#34]
Hi - the container is working great and functional so far. it does a great job when can keep online, the problem I'm facing is that after a few minutes without processing queries or being idle like no one is using it the logs start showing entries like this: 

2023-10-13T01:37:49Z ERR EOF service=http 

and then, became totally unresponsive and need to restart the container to start working again.  any idea why this may happen or do you know any workaround to keep it from losing the connection like this?

**Comment by Seji64** [comment]
Hm, i have the Container Running on Kubernetes and on "normal" Docker and do Not have any of these issues. Is the Docker deamon logs something?

**Comment by hogmac** [comment]
in fact seems related to [https://github.com/mosajjal/sniproxy/issues/76](url) however from my testing i pulled an older snidust image [https://github.com/users/seji64/packages/container/snidust/103503017?tag=sha-40ae16a](url) and that seems to work better as it only had a couple of hiccups in the last 12 hrs.

`PowerDNS DNSDist Security Update Mandatory: Upgrade now, see https://blog.cloudflare.com/technical-breakdown-http2-rapid-reset-ddos-attack/
PowerDNS DNSDist Security Update Mandatory: Upgrade now, see https://blog.cloudflare.com/technical-breakdown-http2-rapid-reset-ddos-attack/
PowerDNS DNSDist Security Update Mandatory: Upgrade now, see https://blog.cloudflare.com/technical-breakdown-http2-rapid-reset-ddos-attack/
2023-10-13T07:10:59Z ERR http: no Host in request URL service=http
2023-10-13T07:15:07Z ERR http: no Host in request URL service=http
PowerDNS DNSDist Security Update Mandatory: Upgrade now, see https://blog.cloudflare.com/technical-breakdown-http2-rapid-reset-ddos-attack/
PowerDNS DNSDist Security Update Mandatory: Upgrade now, see https://blog.cloudflare.com/technical-breakdown-http2-rapid-reset-ddos-attack/
PowerDNS DNSDist Security Update Mandatory: Upgrade now, see https://blog.cloudflare.com/technical-breakdown-http2-rapid-reset-ddos-attack/`

not sure what has changed in newly images that is causing this issues.  As a reference I'm on `Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1`.  I will keep testing the image version I pulled to see if becomes more stable at some point.

**Comment by Seji64** [comment]
please note replacing sniproxy with nginx resulted in a **breaking change**. nginx is listening on port **8080** (before 80) and **8443** (before 443). Ensure you update your docker configuration accordingly!
