### ISSUE TITLE
Localhost socks5

### ISSUE THREAD

**Issue by iriszz1** [Seji64/SniDust#35]
hi~

how do i make sniproxy use localhost socks5 proxy for http/s upstream? it seems like docker cant access local proxy.

is there any workaround to get sniproxy use socks5?

**Comment by alstolten** [comment]
Hi @iriszz1 took me some time. It only works if you attach the snidust container to the host network. In addition you need to pass the environment variable `SNIPROXY_GENERAL__UPSTREAM_SOCKS5` to the container.
So if you use:
```
docker run --network=host -e SNIPROXY_GENERAL__UPSTREAM_SOCKS5="socks5://localhost:<socks-port>" ...
```
the container will run in the host network context, ie can reach localhost and other addresses reachable by the host.
