### ISSUE TITLE
SniDust + Adguard Home

### ISSUE THREAD

**Issue by YBS-PC** [Seji64/SniDust#38]
I use Adguard Home on my VPS because I need DOH on the client. Can I use SniDust + Adguard Home on one VPS? 
For example:
1) create a client in Adguard Home with the name "redirect" (then the iphone client will have doh configured https://myvps/dns-query/redirect ) and specify the dns server 127.0.0.1:5300 for it
2) SniDust listens on port 5300 and accepts a dns request from Adguard Home
3) the upstream DNS server for SniDust is specified on 127.0.0.1:53
4) Adguard Home accepts these requests from SniDust and sends them to its upstream DNS servers specified in Adguard Home by default.

**Comment by Seji64** [comment]
Could work Like this. Just a Note: dndist also Support DoH - maybe a Fork with a customized dnsdist config is the better option.

**Comment by YBS-PC** [comment]
I'm new to this. Could you please explain how to set it up correctly in Snidest? Since I do not know dnsdist and am used to the Adguard interface, I would like to configure exactly the bundle that I indicated in the first message.
 I couldn't even figure out why these ports are needed -p 443:443 -p 80:80 .

**Comment by Seji64** [comment]
No Sorry, i will Not provide tech Support for something Like this. Port 443/80 is needed for SNI. https://www.cloudflare.com/de-de/learning/ssl/what-is-sni/
