### ISSUE TITLE
Cron permission error

### ISSUE THREAD

**Issue by fir3drag0n** [Seji64/SniDust#48]
Hi there,

Unfortunately, I get this error

`[INFO] DynDNS Address in ALLOWED_CLIENTS detected => Enable cron job /entrypoint.sh: line 37: /etc/crontabs/snidust: Permission denied`

and the container is unable to start

How to solve this?
Many thanks in advance!

**Comment by Seji64** [comment]
Oh, thats cause of i switched to non-root. Thats a bug i Need to fix.
