### ISSUE TITLE
Some domain cannot be resolved

### ISSUE THREAD

**Issue by scopolamine1401** [Seji64/SniDust#6]
Dear sir,

When access some websites, even though I added the domain to the list. It just does not work

Request URL: https://sgn-fpt-002-ca204.vieon.vn/307f592e6d9c319ee920edf96f033500/1661467072634/ott-vod-2022/vod/2022/08/08/da66241f-fe1f-4723-8fed-a04c0915af51/media-video-avc1-1.mp4
Request Method: GET
Status Code: 404 
Remote Address: 103.82.27.145:443
Referrer Policy: no-referrer-when-downgrade

Can you tell me how can I debug to find out what happened?

```
[SniDust] Adding domain sgn-fpt-002-ca204.vieon.vn to list
[SniDust] Adding domain sgn-fpt-002.vieon.vn to list
[SniDust] Adding domain hni-fpt-002.vieon.vn to list
[SniDust] Adding domain sentry.vieon.vn to list
[SniDust] Adding domain vieon-tracking.vieon.vn to list
[SniDust] Complete!
Added downstream server 1.1.1.1:53
Added downstream server 1.0.0.1:53
Added downstream server 8.8.8.8:53
Added downstream server 8.8.4.4:53
Listening on 0.0.0.0:5300
dnsdist 1.7.1 comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2
ACL allowing queries from: 127.0.0.1/32, 173.17.67.109/32
Console ACL allowing connections from: 127.0.0.0/8, ::1/128
Webserver launched on 127.0.0.1:8083
Marking downstream 8.8.4.4:53 as 'up'
Marking downstream 1.0.0.1:53 as 'up'
Marking downstream 8.8.8.8:53 as 'up'
Marking downstream 1.1.1.1:53 as 'up'
Polled security status of version 1.7.1 at startup, no known issues reported: OK
Marking downstream 1.1.1.1:53 as 'down'
Marking downstream 1.0.0.1:53 as 'down'
Marking downstream 8.8.8.8:53 as 'down'
Marking downstream 8.8.4.4:53 as 'down'
Marking downstream 1.1.1.1:53 as 'up'
Marking downstream 1.0.0.1:53 as 'up'
Marking downstream 8.8.4.4:53 as 'up'
Marking downstream 8.8.8.8:53 as 'up'
Marking downstream 1.1.1.1:53 as 'down'
Marking downstream 1.0.0.1:53 as 'down'
Marking downstream 8.8.8.8:53 as 'down'
Marking downstream 8.8.4.4:53 as 'down'
Marking downstream 1.0.0.1:53 as 'up'
Marking downstream 1.1.1.1:53 as 'up'
Marking downstream 8.8.8.8:53 as 'up'
Marking downstream 8.8.4.4:53 as 'up'
```

**Comment by Seji64** [comment]
When i request the url **without** snidust i get an `403 Forbidden` error. You get an `404 Not Found`error. So i think SniDust works - the file just does not exist.

**Comment by scopolamine1401** [comment]
I got this error: CORS Missing Allow Origin
When I tried controld.com as smartdns it works so I think there is something to fix here

**Comment by scopolamine1401** [comment]
I tried to look online and found some people faced this as well 
https://github.com/dlundquist/sniproxy/issues/388

**Comment by scopolamine1401** [comment]
Some thing more

https://anton.belodedenko.me/netflix-proxy-geo-unblocker/#comment-5795018361

`1)Failed to load resource: the server responded with a status of 404 ()
2)Access to fetch at '[https://uapi.zee5.com/v1/us...](https://disq.us/url?url=https%3A%2F%2Fuapi.zee5.com%2Fv1%2Fuser%2Fdatacollection%27%3AlSpl0I3ieIHE0h7Y54SPk0vkxkk&cuid=3587986) from origin '[https://www.zee5.com](https://disq.us/url?url=https%3A%2F%2Fwww.zee5.com%3A_gIMZb41Pg4xvVyeKMEUERKiZu8&cuid=3587986)' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
3)CleverTap error: Age value should be a number. This property has been ignored
4)net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH`

**Comment by ULIYAN1** [comment]
I am having the same issue with Hulu on Chrome. I can log in to Hulu homepage but I cannot play any video content due to CORS issues with play.hulu.com and many other Hulu sub-domains. Any idea how to fix CORS issues ?

**Comment by Seji64** [comment]
No, not really. i just the put the parts of dnidist and sniproxy togheter. sadly can't help with issues regarding sniproxy.

**Comment by Seji64** [comment]
@ULIYAN1: Maybe you want to try [https://github.com/mosajjal/sniproxy](https://github.com/mosajjal/sniproxy) ? (found it while googling a bit)

Maybe in this rewrite the HTTP2/CORS issue does not exist.

**Comment by Seji64** [comment]
@ULIYAN1 i made a few changes in the dev branch. Could please test if it resolves your issue? You need to pull the image with the `dev` tag.

**Comment by Seji64** [comment]
I replaced snidust with a kind of fork (https://github.com/mosajjal/sniproxy ) this issue should now be fixed.
