### ISSUE TITLE
Abuse on ubuntu

### ISSUE THREAD

**Issue by Mousaaa11** [Seji64/SniDust#61]
![Screenshot 2024-07-07 191453](https://github.com/Seji64/SniDust/assets/157221259/e9d17130-8bd7-486f-9ac2-85fb94dacb04)

I got abused by AWS after running the script

**Comment by Seji64** [comment]
And? Thats not really a "issue"...

**Comment by Seji64** [comment]
Sorry guys, but that's not a problem with this project. If your provider doesn't allow you to run proxy services, then that's the way it is. The same would happen if you install a SOCKS service or something similar. I cannot and will not support you in this regard.
