### ISSUE TITLE
Add DoT support

### ISSUE THREAD

**Issue by Seji64** [Seji64/SniDust#76]
_Originally requested by @millad221 in https://github.com/Seji64/SniDust/discussions/74#discussioncomment-10650852_

**Comment by Seji64** [comment]
DoH is too complicated / not possible cause already listening to 443 for * all * domains (cause thats what a sniproxy is doing). So i will stick to DoT

**Comment by millad221** [comment]
> DoH is too complicated / not possible cause already listening to 443 for * all * domains (cause thats what a sniproxy is doing). So i will stick to DoT

During my test, unfortunately, many games do not open on Steam and remain on the login screen. It would be great to solve this problem.

**Comment by Seji64** [comment]
ok, its not ready yet....have to fix some things...

**Comment by millad221** [comment]
> ok, its not ready yet....have to fix some things...

Yes, I can test whenever you say
Now the most important issue is the opening of games on steam, which is not possible with image 1.0.14, will you check this issue as well?

**Comment by Seji64** [comment]
Thats something completely different. Pls don't mix things up. Open another issue

**Comment by millad221** [comment]
I realized that I will check the new version, if it doesn't work properly, I will open another ticket

**Comment by millad221** [comment]
I did the test
The first problem is that it is not possible to receive an IP from the myacl list and nginx gives error number 2
The second problem is that I run the new Docker file by default, traffic is not exchanged

**Comment by Seji64** [comment]
just saying "does not work" does NOT help. Logs, your configuration, environment and so on...however my tests were posetive
