### ISSUE TITLE
Game consoles support

### ISSUE THREAD

**Issue by masoudmghd** [Seji64/SniDust#80]
Is there any chance that SniDust will be supporting Game Consoles like XBOX?

As you may know some games use UDP streams which can't be pass by nginx because of the lack of tls headers. Also, there are so many ports being used by every other games.

Xbox ports : https://support.xbox.com/en-gb/help/hardware-network/connect-network/network-ports-used-xbox-live

- What are the chances?
- Is there anything to contribute?

**Comment by Seji64** [comment]
You answered it yourself - UDP lacks of tls headers. So no not possible.
