### ISSUE TITLE
Modular site lists

### ISSUE THREAD

**Issue by EZarnosky** [Seji64/SniDust#9]
Rather than one large list that would nee to be constantly updated. It would be great it if the site lists can be done as separate files for each services (ex. Netflix - all domains used for streaming Netflix, Disney+ - all required domains). It would allow for people to keep everything more organized and remove what they don't need.

A reload option for the list would be great too, something that does not require me to restart the docker container.

**Comment by Seji64** [comment]
> Rather than one large list that would nee to be constantly updated. It would be great it if the site lists can be done as separate files for each services (ex. Netflix - all domains used for streaming Netflix, Disney+ - all required domains). It would allow for people to keep everything more organized and remove what they don't need.
Good Idea, will try to implement this.

> A reload option for the list would be great too, something that does not require me to restart the docker container.

This already exists, but is poorly documented. I think i need to overhaul the readme a bit
